---
- name: Deploy Kubernetes Application
  hosts: appserver  # Replace with your target Kubernetes master host or group
  gather_facts: no  # No need to gather facts for this playbook
  become: yes 
  
  tasks:
    - name: Copy deployment.yaml to Kubernetes master
      ansible.builtin.copy:
        src: /var/lib/jenkins/workspace/job1/Ansible/deployment.yaml  # Adjust path as per your Jenkins workspace
        dest: /home/ec2-user/deployment.yaml
        remote_src: yes  # This is used to indicate the source file is on the Ansible controller

    - name: Apply Deployment
      ansible.builtin.command: kubectl apply -f /home/ec2-user/deployment.yaml

